In [3]:
import os
import glob
import numpy as np

In [2]:
if __name__ == "__main__":
    data_dir = '/home/afguerrerohernan/data/patients/'
    data_dir_output = '/home/afguerrerohernan/data/patients_processed'
    
    for np_name in glob.glob(os.path.join(data_dir, '*.np[yz]')):
        with np.load(np_name) as data:
            i, = np.where(np.argmax(data['Y'], axis=1) == 5)
            print 'Found %d elements with stage 6' % (len(i))
            new_Y = np.delete(np.delete(data['Y'], i, axis=0), 5, axis=1)
            new_X = np.delete(data['X'], i, axis=0)
            new_np_name = os.path.join(data_dir_output, os.path.basename(np_name))
            np.savez(new_np_name, X=new_X, Y=new_Y)

Found 5 elements with stage 6
Found 7 elements with stage 6
Found 0 elements with stage 6
Found 0 elements with stage 6
Found 1 elements with stage 6
Found 1 elements with stage 6
Found 5 elements with stage 6
Found 0 elements with stage 6
Found 2 elements with stage 6
Found 0 elements with stage 6
Found 0 elements with stage 6
Found 2 elements with stage 6
Found 9 elements with stage 6
Found 0 elements with stage 6
Found 0 elements with stage 6
Found 1 elements with stage 6
Found 0 elements with stage 6
Found 0 elements with stage 6
Found 22 elements with stage 6
Found 5 elements with stage 6


In [4]:
def unfold(data):
    y = np.array(data[0]['Y'])
    for item in data[1:]:
        y = np.concatenate((y, item['Y']))
    return y

def load_data(path):
    # Load all npz files from path
    return np.array([np.load(np_name) for np_name in glob.glob(os.path.join(path, '*.np[yz]'))])

In [6]:
import sklearn
data_dir_output = '/home/afguerrerohernan/data/patients_processed'
data = load_data(data_dir_output)

In [33]:
y = unfold(data)

In [34]:
y.shape

(36269, 5)

In [40]:
y_1 = np.argmax(y, axis=1)

In [41]:
class_weight = sklearn.utils.compute_class_weight('balanced', np.arange(5), y_1)

In [42]:
class_weight

array([ 2.69457652,  0.40896431,  1.27215012,  2.98019721,  0.94156282])

In [20]:
y

array([0, 0, 0, ..., 4, 3, 4])

In [38]:
cw = sklearn.utils.compute_sample_weight({0:0,1:1,2:2,3:3,4:4}, y)

ValueError: For multi-output, class_weight should be a list of dicts, or a valid string.

In [36]:
cw

array([ 1.33069142,  1.33069142,  1.33069142, ...,  0.39557467,
        1.48305114,  0.39557467])